// embed_runtime -- build-time-only tool, NOT part of the 3b compiler itself.
//
// Reads each file named on argv (e.g. `runtime/bbb_arena.c`) and writes a
// generated C header to stdout containing one `static const char* const
// NAME[] = { "line1\n", "line2\n", ..., NULL };` array per file (one
// string literal per input LINE, byte-escaped so it round-trips exactly).
// NAME is the input path with every non-alnum character folded to `_` (so
// `runtime/bbb_arena.c` becomes `g_embed_runtime_bbb_arena_c`).
//
// Deliberately an ARRAY of short per-line literals rather than one giant
// concatenated string -- adjacent string literals are merged by the
// preprocessor for -Wpedantic's ISO C99 4095-char single-literal limit
// (`-Woverlength-strings`), so splitting into "..." "..." pieces doesn't
// dodge that warning the way splitting into separate ARRAY ELEMENTS does.
// codegen.c's cg_fputs_lines just fputs each element in turn.
//
// This lets codegen.c's cg_write_runtime_header/cg_write_runtime_source
// emit the real runtime/bbb_*.{h,c} module files' contents into a build's
// generated 3b_runtime.h/.c WITHOUT the 3b binary needing those files to
// exist on disk at all -- they're baked into the compiler's own binary at
// 3b's OWN build time instead. See the Makefile rule that runs this before
// compiling codegen.c.
//
// Deliberately dependency-free (no base.h) -- this only ever runs as part
// of building the 3b compiler itself, not as part of 3b compiling anything.

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <ctype.h>

static void
sanitized_ident(const char* path, char* out, size_t out_size) {
  size_t i = 0;
  out[i++] = 'g'; out[i++] = '_'; out[i++] = 'e'; out[i++] = 'm';
  out[i++] = 'b'; out[i++] = 'e'; out[i++] = 'd'; out[i++] = '_';
  for (const char* p = path; *p && i + 1 < out_size; p++) {
    out[i++] = isalnum((unsigned char)*p) ? *p : '_';
  }
  out[i] = 0;
}

static int
embed_one(const char* path) {
  FILE* f = fopen(path, "rb");
  if (!f) {
    fprintf(stderr, "embed_runtime: could not open '%s'\n", path);
    return 1;
  }

  char ident[512];
  sanitized_ident(path, ident, sizeof(ident));

  printf("static const char* const %s[] = {\n\"", ident);
  int c;
  while ((c = fgetc(f)) != EOF) {
    switch (c) {
      case '\\': printf("\\\\"); break;
      case '"':  printf("\\\""); break;
      case '\n': printf("\\n\",\n\""); break; // one array element per source line
      case '\r': printf("\\r"); break;
      case '\t': printf("\\t"); break;
      default:
        if (c < 0x20 || c >= 0x7f) printf("\\x%02x", (unsigned char)c);
        else                       putchar(c);
        break;
    }
  }
  printf("\",\nNULL };\n\n");

  fclose(f);
  return 0;
}

int
main(int argc, char** argv) {
  printf("// Generated by tools/embed_runtime -- do not edit by hand.\n");
  printf("// Regenerated automatically by `make` whenever runtime/*.h or runtime/*.c change.\n\n");
  int status = 0;
  for (int i = 1; i < argc; i++) {
    if (embed_one(argv[i]) != 0) status = 1;
  }
  return status;
}
